declare module "nprogress"
declare module "lodash-es"
declare module 'markdown-it-ins'
declare module 'markdown-it-abbr'
declare module 'markdown-it-sub'
declare module 'markdown-it-sup'
declare module 'markdown-it-task-lists'
declare module 'markdown-it-deflist'
declare module 'markdown-it-mermaid'
declare module 'markdown-it-mark'
declare module 'markdown-it-footnote'
declare module 'markdown-it-container'
declare module 'vue-echarts'
declare module 'markdown-it-katex'